language: node_js
node_js:
    - "6"
sudo: false
env:
    global:
        - secure: "LUZnP+lhVj0zbFe/tSppMvI6jaXyOos84WZehPImMeara9/RRrRk5QpKsUsqr1x/oHzElJnbAX9OD/GOuEI4fyYv9qBXr8CKxBpmjlM2ElY85WcGm9mntRXtvR0iscR3Jg9kPtUBqzVlh1E/mQjs5GR2nLn0Fe34Xwl6TWd3m6c="
        - DISPLAY=':99.0'
        - FIREFOX_BINARY='./firefox/firefox'
        - PATH="./firefox/:${PATH}"
        - CXX=g++-4.8
    matrix:
        - FIREFOX_RELEASE='release-linux64-add-on-devel'
        - FIREFOX_RELEASE='nightly-latest'
        - FIREFOX_RELEASE='aurora-latest'
        - FIREFOX_RELEASE='49.0'
        - FIREFOX_RELEASE='esr-latest'
        #- FIREFOX_RELEASE='beta-linux64-add-on-devel'

# pulled in by node-webcrypto-ossl@1.0.7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

matrix:
    fast_finish: true
    allow_failures:
        - env: FIREFOX_RELEASE='nightly-latest'
        - env: FIREFOX_RELEASE='aurora-latest'
        #- env: FIREFOX_RELEASE='esr-latest'
cache:
    directories:
        - node_modules
before_script:
    - test $FIREFOX_RELEASE != nightly-latest               || wget -O firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != aurora-latest                || wget -O firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != beta-linux64-add-on-devel    || bash -x scripts/fetch-unbranded.sh $FIREFOX_RELEASE
    - test $FIREFOX_RELEASE != release-linux64-add-on-devel || bash -x scripts/fetch-unbranded.sh $FIREFOX_RELEASE
    - test $FIREFOX_RELEASE != '49.0'                       || wget -O firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != esr-latest                   || wget -O firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - tar xvf firefox-$FIREFOX_RELEASE.tar.bz2
    - sh -e /etc/init.d/xvfb start
install:
    - npm install --no-optional
script:
    - npm run build
    - npm test
    - npm run clean
    - npm run lint
